// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzxuktbncnlemfotamxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6eHVrdGJuY25sZW1mb3RhbXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTEyNDYsImV4cCI6MjA2MTE2NzI0Nn0.QvZIQABNeuZw7GygiqEvI32eMF9q_Lu5A_QgRWrj598";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);